### ISSUE TITLE
Verilator cache does not re-use cached Verilator binary across tests

### ISSUE THREAD

**Issue by oharboe** [ucb-bar/chisel-testers2#379] opened 2021-08-18 09:52 UTC
To reproduce, check out #378, then run:

```
sbt "test:testOnly *VerilatorCachingTests*"
[deleted]
 - should re-use cached verilator from another test *** FAILED ***
[info]   0 did not equal 1 (VerilatorCachingTests.scala:34)

```

**Comment by ekiwi** [comment] 2021-11-02 21:32
duplicate of https://github.com/ucb-bar/chisel-testers2/issues/380

**Closed by ekiwi** 2021-11-02 21:32 UTC
